# Generated by Django 4.1.3 on 2022-11-17 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studios.studio'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
    ]
